# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_list_item.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.resize(279, 50)
        self.horizontalLayoutWidget = QtWidgets.QWidget(widget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 281, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.title_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.horizontalLayout.addWidget(self.title_label)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.detail_info_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.detail_info_label.setAlignment(QtCore.Qt.AlignCenter)
        self.detail_info_label.setObjectName("detail_info_label")
        self.verticalLayout_2.addWidget(self.detail_info_label)
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.horizontalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "Form"))
        self.title_label.setText(_translate("widget", "TextLabel"))
        self.detail_info_label.setText(_translate("widget", "TextLabel"))
        self.pushButton.setText(_translate("widget", "PushButton"))
